apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-sugrfree
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backend-sugrfree
    spec:
      containers:
        - image: trevahok/sugrfree:v1
          imagePullPolicy: Always
          name: backend-sugrfree
          ports:
            - containerPort: 8000

