apiVersion: v1
kind: Service
metadata:
        name: backend-service-lb
spec:
        type: LoadBalancer
        ports:
                - port: 8000
                  protocol: TCP
                  targetPort: 8000
        selector:
                app:  backend-sugrfree