apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-sugrfree
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
  template:
          metadata:
                  labels:
                    app: backend-sugrfree
          spec:
                  containers:
                          - image: trevahok/todorest:gunicorn
                            imagePullPolicy: Always
                            name: backend-django
                            ports:
                                    - containerPort: 8000

